from typing import Optional
from ._argparsers import MacroStandardArgsParser as MacroStandardArgsParser, ParsedMacroArgs as ParsedMacroArgs, ParsedVerbatimArgs as ParsedVerbatimArgs, VerbatimArgsParser as VerbatimArgsParser

from _typeshed import Incomplete
from collections.abc import Generator, Iterable

def unicode(s): ...

class MacroSpec:
    macroname: Incomplete
    args_parser: Incomplete
    def __init__(
        self, 
        macroname: str, 
        args_parser: MacroStandardArgsParser =..., 
        **kwargs
    ) -> None: ...
    def parse_args(self, *args, **kwargs): ...

class EnvironmentSpec:
    environmentname: Incomplete
    args_parser: Incomplete
    is_math_mode: Incomplete
    def __init__(self, environmentname, args_parser=..., is_math_mode: bool = False, **kwargs) -> None: ...
    def parse_args(self, *args, **kwargs): ...

class SpecialsSpec:
    specials_chars: Incomplete
    args_parser: Incomplete
    def __init__(self, specials_chars, args_parser=None, **kwargs) -> None: ...
    def parse_args(self, *args, **kwargs): ...

def std_macro(macname, *args, **kwargs): ...
def std_environment(envname, *args, **kwargs): ...
def std_specials(specials_chars): ...

class LatexContextDb:
    category_list: Incomplete
    d: Incomplete
    unknown_macro_spec: Incomplete
    unknown_environment_spec: Incomplete
    unknown_specials_spec: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def add_context_category(
        self, 
        category: Optional[str], 
        macros: Iterable[MacroSpec] = [], 
        environments=[], 
        specials=[], 
        prepend: bool = False, 
        insert_before=None, 
        insert_after=None
    ) -> None: ...
    def set_unknown_macro_spec(self, macrospec) -> None: ...
    def set_unknown_environment_spec(self, environmentspec) -> None: ...
    def set_unknown_specials_spec(self, specialsspec) -> None: ...
    def categories(self): ...
    def get_macro_spec(self, macroname): ...
    def get_environment_spec(self, environmentname): ...
    def get_specials_spec(self, specials_chars): ...
    def test_for_specials(self, s, pos, parsing_state=None): ...
    def iter_macro_specs(self, categories=None) -> Generator[Incomplete]: ...
    def iter_environment_specs(self, categories=None) -> Generator[Incomplete]: ...
    def iter_specials_specs(self, categories=None) -> Generator[Incomplete]: ...
    def filter_context(self, keep_categories=[], exclude_categories=[], keep_which=[]): ...
