import types
from _typeshed import Incomplete
from typing import Optional

from pylatexenc.macrospec import LatexContextDb
from pylatexenc.macrospec._argparsers import ParsedMacroArgs

def unicode(string): ...

logger: Incomplete

class LatexWalkerError(Exception): ...

class LatexWalkerParseError(LatexWalkerError):
    input_source: Incomplete
    msg: Incomplete
    s: Incomplete
    pos: Incomplete
    lineno: Incomplete
    colno: Incomplete
    open_contexts: Incomplete
    def __init__(self, msg, s=None, pos=None, lineno=None, colno=None) -> None: ...

class LatexWalkerEndOfStream(LatexWalkerError):
    final_space: Incomplete
    def __init__(self, final_space: str = '') -> None: ...

def get_default_latex_context_db(): ...
def MacrosDef(macname, optarg, numargs): ...

default_macro_dict: Incomplete

class LatexToken:
    tok: Incomplete
    arg: Incomplete
    pos: Incomplete
    len: Incomplete
    pre_space: Incomplete
    post_space: Incomplete
    def __init__(self, tok, arg, pos, len, pre_space, post_space: str = '') -> None: ...
    def __unicode__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    __hash__: Incomplete

class LatexNode:
    parsing_state: Incomplete
    pos: int
    len: int
    def __init__(self, _fields, _redundant_fields=None, parsing_state=None, pos=None, len=None, **kwargs) -> None: ...
    def nodeType(self): ...
    def isNodeType(self, t): ...
    def latex_verbatim(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    __hash__: Incomplete
    def __unicode__(self): ...

class LatexCharsNode(LatexNode):
    chars: str
    def __init__(self, chars, **kwargs) -> None: ...
    def nodeType(self): ...

class LatexGroupNode(LatexNode):
    nodelist: Incomplete
    delimiters: Incomplete
    def __init__(self, nodelist, **kwargs) -> None: ...
    def nodeType(self): ...

class LatexCommentNode(LatexNode):
    comment: Incomplete
    comment_post_space: Incomplete
    def __init__(self, comment, **kwargs) -> None: ...
    def nodeType(self): ...

class LatexMacroNode(LatexNode):
    macroname: str
    nodeargd: ParsedMacroArgs
    macro_post_space: Incomplete
    nodeoptarg: Incomplete
    nodeargs: Incomplete
    def __init__(self, macroname: str, **kwargs) -> None: ...
    def nodeType(self): ...

class LatexEnvironmentNode(LatexNode):
    environmentname: str
    nodelist: list[LatexNode]
    nodeargd: Incomplete
    envname: Incomplete
    optargs: Incomplete
    args: Incomplete
    def __init__(self, environmentname, nodelist, **kwargs) -> None: ...
    def nodeType(self): ...

class LatexSpecialsNode(LatexNode):
    specials_chars: Incomplete
    nodeargd: Incomplete
    def __init__(self, specials_chars, **kwargs) -> None: ...
    def nodeType(self): ...

class LatexMathNode(LatexNode):
    displaytype: Incomplete
    nodelist: list[LatexNode]
    delimiters: Incomplete
    def __init__(self, displaytype, nodelist=[], **kwargs) -> None: ...
    def nodeType(self): ...

class _PushPropOverride:
    obj: Incomplete
    propname: Incomplete
    new_value: Incomplete
    def __init__(self, obj, propname, new_value) -> None: ...
    initval: Incomplete
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class ParsingState:
    s: Incomplete
    latex_context: Incomplete
    in_math_mode: bool
    math_mode_delimiter: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def sub_context(self, **kwargs): ...
    def get_fields(self): ...

class LatexWalker:
    s: str
    debug_nodes: bool
    default_parsing_state: Incomplete
    tolerant_parsing: Incomplete
    strict_braces: Incomplete
    def __init__(
        self, 
        s: str, 
        latex_context: Optional[LatexContextDb] = None, 
        **kwargs
    ) -> None: ...
    def make_parsing_state(self, **kwargs): ...
    def parse_flags(self): ...
    def get_token(self, pos, include_brace_chars=None, environments: bool = True, keep_inline_math=None, parsing_state=None, **kwargs): ...
    def make_node(self, node_class, **kwargs): ...
    def pos_to_lineno_colno(self, pos, as_dict: bool = False): ...
    def get_latex_expression(self, pos, strict_braces=None, parsing_state=None): ...
    def get_latex_maybe_optional_arg(self, pos, parsing_state=None): ...
    def get_latex_braced_group(self, pos, brace_type: str = '{', parsing_state=None): ...
    def get_latex_environment(self, pos, environmentname=None, parsing_state=None): ...
    pos: Incomplete
    parsing_state: Incomplete
    lastchars: Incomplete
    lastchars_pos: Incomplete
    def get_latex_nodes(
        self, 
        pos: int = 0, 
        stop_upon_closing_brace=None, 
        stop_upon_end_environment=None, 
        stop_upon_closing_mathmode=None, 
        read_max_nodes=None, 
        parsing_state=None
    ) -> tuple[list[LatexNode], int, int]: ...

def get_token(s, pos, brackets_are_chars: bool = True, environments: bool = True, **parse_flags): ...
def get_latex_expression(s, pos, **parse_flags): ...
def get_latex_maybe_optional_arg(s, pos, **parse_flags): ...
def get_latex_braced_group(s, pos, brace_type: str = '{', **parse_flags): ...
def get_latex_environment(s, pos, environmentname=None, **parse_flags): ...
def get_latex_nodes(s, pos: int = 0, stop_upon_closing_brace=None, stop_upon_end_environment=None, stop_upon_closing_mathmode=None, **parse_flags): ...
def nodelist_to_latex(nodelist): ...
def put_in_braces(brace_char, thestring): ...
def disp_node(n, indent: int = 0, context: str = '* ', skip_group: bool = False) -> None: ...
def make_json_encoder(latexwalker, use_line_numbers: bool = True): ...
